# Generated by Django 3.2.8 on 2021-12-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_model',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
